name: CI
on:
  push:
    branches:
      - master

jobs:
  
  ci:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout source code
        uses: actions/checkout@v2
      
      - name: Build
        run: yarn install && yarn build
      
      - name: Deploy to GitHub Gist
        uses: exuanbo/actions-deploy-gist@v1.0.4
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 9a7b3990751df4c312c8e9ace05a8faf
          gist_file_name: sw.html
          file_path: ./dist/index.html
